### ISSUE TITLE
TypeError while importing tcmb 0.4.0

### ISSUE THREAD

**Issue by sametsoekel** [kaymal/tcmb#14]
`import tcmb`

raises this error in Python 3.9.12;

```

def wildcard_search(
pattern: str, items: list | None = None, use_package_data: bool = True
) -> list:
 """Search for items using regex pattern that can contain wildcard characters.
 
Parameters
(...)

 """
if items is None:

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

This syntax is only supported for Python 3.10 or later.

Can you please replace this function parts with typing.Optional for Python version compatibility ? ([example](https://stackoverflow.com/a/51710151))

Since I got a live app that works depending on your package, I can at least create a PR if you let me know.

Thanks

**Comment by kaymal** [comment]
Thanks @sametsoekel ! I'll add `from __future__ import annotations` to make Union operator available for earlier versions of Python.

**Comment by kaymal** [comment]
I've fixed this one, however feel free to create a PR for any issues or features in the future @sametsoekel .

**Comment by sametsoekel** [comment]
agreed ! 🤝
